### ISSUE TITLE
AWS services 

### ISSUE THREAD

**Issue by apierr** [devw/customize-theme#2]
### Sub-tasks
- [x] get the list of themes from DynamoDB
- [x] register a shop in DynamoDB
- [x] write a file in Amazon S3
- [ ] check that the shop exists in the db (AWS.DynamoDB))
- [ ] if the shop does not exist, create a record in the db with shop name, theme_id (default), access_token (AWS.DynamoDB)
- [ ] inject the scriptTag (if it does not exist)

### DynamoDb
| shop  | theme_id  |  access_toekn  | storefront_token  |
|---|---|---|---|
|   |   | ctx.session.accessToken  |   |
|   |   |   |   |

| theme_id  |  theme_name   |
|---|---|
| | |

References: [Amazon API Gateway](https://www.youtube.com/playlist?list=PL5KTLzN85O4ISx9guOjbynlhCxB87xmUq)
